name: release

on:
  push:


permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - uses: sergeysova/jq-action@a3f0d4ff59cc1dddf023fc0b325dd75b10deec58 #v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ">=1.17.0"
      - name: Set up Python
        uses: actions/setup-python@v2
      - run: pip install yq jq
      - name: Set environment variables
        run: echo "GOVERSION=$(go env GOVERSION)" >> $GITHUB_ENV
      - name: Run tests
        run: make test
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b #v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b #v2
        if: "!startsWith(github.ref, 'refs/tags')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot
      - name: Build Helm plugin
        run: make plugin
      - name: Publish Helm Dump plugin
        uses: actions/upload-artifact@v2
        with:
          name: helm-dump-plugin
          path: "dist/plugin/*"
      - name: Upload bundles to release
        uses: svenstaro/upload-release-action@cc92c9093e5f785e23a3d654fe2671640b851b5f #v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file: "dist/plugin/artifacts/*"
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          file_glob: true